-- 사용할 데이터베이스 설정
USE DATABASE MY_HACKATHON_DB;
-- 사용할 스키마 설정
USE SCHEMA PUBLIC;
-- 사용할 웨어하우스(컴퓨팅 리소스) 설정
USE WAREHOUSE COMPUTE_WH;



-- 서울시 주요 3대 백화점 방문 데이터를 해커톤 작업용 데이터베이스로 복사
-- 원본 테이블: LOPLAT_DB.PUBLIC.SNOWFLAKE_STREAMLIT_HACKATHON_LOPLAT_DEPARTMENT_STORE_DATA
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.DEP_STORE_DATA AS
SELECT * FROM LOPLAT_DB.PUBLIC.SNOWFLAKE_STREAMLIT_HACKATHON_LOPLAT_DEPARTMENT_STORE_DATA;

-- 백화점 방문 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.DEP_STORE_DATA;



-- 서울시 유동 인구 데이터(SPH 제공)를 로컬 DB로 복사
-- 원본 테이블: SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.FLOATING_POPULATION_INFO
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA AS
SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.FLOATING_POPULATION_INFO;

-- 서울시 유동 인구 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA;



-- 서울시 카드 소비 데이터(SPH 제공)를 로컬 DB로 복사
-- 원본 테이블: SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA AS
SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO;

-- 서울시 카드 소비 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA;



-- 서울시 지역 데이터(SPH 제공)를 로컬 DB로 복사
-- 원본 테이블: SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA AS
SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST;

-- 서울시 지역 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA;



-- 테이블 컬럼 목록 확인
DESC TABLE MY_HACKATHON_DB.PUBLIC.DEP_STORE_DATA;
DESC TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA;
DESC TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA;
DESC TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA;

