-- 사용할 데이터베이스 설정
USE DATABASE MY_HACKATHON_DB;
-- 사용할 스키마 설정
USE SCHEMA PUBLIC;
-- 사용할 웨어하우스(컴퓨팅 리소스) 설정
USE WAREHOUSE COMPUTE_WH;



-- 서울시 주요 3대 백화점 방문 데이터를 해커톤 작업용 데이터베이스로 복사
-- 원본 테이블: LOPLAT_DB.PUBLIC.SNOWFLAKE_STREAMLIT_HACKATHON_LOPLAT_DEPARTMENT_STORE_DATA
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.DEP_STORE_DATA AS
SELECT * FROM LOPLAT_DB.PUBLIC.SNOWFLAKE_STREAMLIT_HACKATHON_LOPLAT_DEPARTMENT_STORE_DATA;

-- 백화점 방문 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.DEP_STORE_DATA;



-- 서울시 유동 인구 데이터(SPH 제공)를 로컬 DB로 복사
-- 원본 테이블: SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.FLOATING_POPULATION_INFO
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA AS
SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.FLOATING_POPULATION_INFO;

-- 서울시 유동 인구 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA;



-- 서울시 카드 소비 데이터(SPH 제공)를 로컬 DB로 복사
-- 원본 테이블: SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA AS
SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO;

-- 서울시 카드 소비 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA;



-- 서울시 지역 데이터(SPH 제공)를 로컬 DB로 복사
-- 원본 테이블: SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA AS
SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST;

-- 서울시 지역 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.SEOUL_REGION_DATA;



-- 서울시 카드 코드 데이터(SPH 제공)를 로컬 DB로 복사
-- 원본 테이블: SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CODE_MASTER
CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.CARD_CODE_DATA AS
SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CODE_MASTER;

-- 서울시 카드 코드 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.CARD_CODE_DATA;



-- 테이블 컬럼 목록 확인
DESC TABLE MY_HACKATHON_DB.PUBLIC.DEP_STORE_DATA;
DESC TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA;
DESC TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA;
DESC TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA;
DESC TABLE MY_HACKATHON_DB.PUBLIC.CARD_CODE_DATA;



-- 서울시 지역 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.REGION_DATA;

-- 서울시 지역 데이터 불필요 컬럼 삭제 (영문 지명, 지역 위치 정보)
ALTER TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA
DROP COLUMN PROVINCE_ENG_NAME;

ALTER TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA
DROP COLUMN CITY_ENG_NAME;

ALTER TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA
DROP COLUMN DISTRICT_ENG_NAME;

ALTER TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA
DROP COLUMN DISTRICT_GEOM;

-- 서울시 지역 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.REGION_DATA;



-- 서울시 카드 소비 데이터 조회
SELECT * FROM MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA;

-- 서울시 카드 소비 데이터와 지역 데이터 조인
SELECT 
    R.PROVINCE_KOR_NAME AS province_name,
    R.CITY_KOR_NAME AS city_name,
    R.DISTRICT_KOR_NAME AS district_name,
    S.*
FROM 
    MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA S
JOIN 
    MY_HACKATHON_DB.PUBLIC.REGION_DATA R
ON 
    S.PROVINCE_CODE = R.PROVINCE_CODE 
    AND S.CITY_CODE = R.CITY_CODE 
    AND S.DISTRICT_CODE = R.DISTRICT_CODE;




CREATE TABLE MY_HACKATHON_DB.PUBLIC.SALES_KOR_LABELING AS
WITH
-- 카드 타입 코드 매핑 (M08: 0=법인, 1=개인)
CARD_TYPE_MAP AS (
    SELECT SUB_CODE AS CARD_TYPE_CODE, SUB_CODE_NAME AS CARD_TYPE_NAME
    FROM MY_HACKATHON_DB.PUBLIC.CARD_CODE_DATA
    WHERE CODE_ID = 'M08'
),

-- 라이프스타일 코드 매핑 (M06)
LIFESTYLE_MAP AS (
    SELECT SUB_CODE AS LIFESTYLE_CODE, SUB_CODE_NAME AS LIFESTYLE_NAME
    FROM MY_HACKATHON_DB.PUBLIC.CARD_CODE_DATA
    WHERE CODE_ID = 'M06'
),

-- 시간대 코드 매핑 (M03)
TIME_SLOT_MAP AS (
    SELECT SUB_CODE AS TIME_SLOT_CODE, SUB_CODE_NAME AS TIME_SLOT_NAME
    FROM MY_HACKATHON_DB.PUBLIC.CARD_CODE_DATA
    WHERE CODE_ID = 'M03'
),

-- 지역 정보 매핑
REGION_MAP AS (
    SELECT 
        PROVINCE_CODE, CITY_CODE, DISTRICT_CODE,
        PROVINCE_KOR_NAME AS PROVINCE_NAME,
        CITY_KOR_NAME AS CITY_NAME,
        DISTRICT_KOR_NAME AS DISTRICT_NAME
    FROM MY_HACKATHON_DB.PUBLIC.REGION_DATA
)

-- 최종 SELECT: 매핑된 값들을 LEFT JOIN하여 출력
SELECT
    -- 지역 정보
    S.PROVINCE_CODE,
    R.PROVINCE_NAME,
    S.CITY_CODE,
    R.CITY_NAME,
    S.DISTRICT_CODE,
    R.DISTRICT_NAME,

    -- 카드 소비 데이터
    S.STANDARD_YEAR_MONTH,
    
    -- 카드 타입 + 매핑된 명칭
    S.CARD_TYPE,
    C.CARD_TYPE_NAME,
    
    -- 기타 인구 특성
    S.WEEKDAY_WEEKEND,
    S.GENDER,
    S.AGE_GROUP,

    -- 시간대 + 매핑
    S.TIME_SLOT,
    T.TIME_SLOT_NAME,

    -- 라이프스타일 + 매핑
    S.LIFESTYLE,
    L.LIFESTYLE_NAME,

    -- 소비 및 횟수 데이터 전체
    S.TOTAL_SALES,
    S.FOOD_SALES,
    S.COFFEE_SALES,
    S.ENTERTAINMENT_SALES,
    S.DEPARTMENT_STORE_SALES,
    S.LARGE_DISCOUNT_STORE_SALES,
    S.SMALL_RETAIL_STORE_SALES,
    S.CLOTHING_ACCESSORIES_SALES,
    S.SPORTS_CULTURE_LEISURE_SALES,
    S.ACCOMMODATION_SALES,
    S.TRAVEL_SALES,
    S.BEAUTY_SALES,
    S.HOME_LIFE_SERVICE_SALES,
    S.EDUCATION_ACADEMY_SALES,
    S.MEDICAL_SALES,
    S.ELECTRONICS_FURNITURE_SALES,
    S.CAR_SALES,
    S.CAR_SERVICE_SUPPLIES_SALES,
    S.GAS_STATION_SALES,
    S.E_COMMERCE_SALES,
    
    S.TOTAL_COUNT,
    S.FOOD_COUNT,
    S.COFFEE_COUNT,
    S.ENTERTAINMENT_COUNT,
    S.DEPARTMENT_STORE_COUNT,
    S.LARGE_DISCOUNT_STORE_COUNT,
    S.SMALL_RETAIL_STORE_COUNT,
    S.CLOTHING_ACCESSORIES_COUNT,
    S.SPORTS_CULTURE_LEISURE_COUNT,
    S.ACCOMMODATION_COUNT,
    S.TRAVEL_COUNT,
    S.BEAUTY_COUNT,
    S.HOME_LIFE_SERVICE_COUNT,
    S.EDUCATION_ACADEMY_COUNT,
    S.MEDICAL_COUNT,
    S.ELECTRONICS_FURNITURE_COUNT,
    S.CAR_SALES_COUNT,
    S.CAR_SERVICE_SUPPLIES_COUNT,
    S.GAS_STATION_COUNT,
    S.E_COMMERCE_COUNT

FROM MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA S

-- 카드 타입 매핑
LEFT JOIN CARD_TYPE_MAP C
ON S.CARD_TYPE = C.CARD_TYPE_CODE

-- 라이프스타일 매핑
LEFT JOIN LIFESTYLE_MAP L
ON S.LIFESTYLE = L.LIFESTYLE_CODE

-- 시간대 매핑
LEFT JOIN TIME_SLOT_MAP T
ON S.TIME_SLOT = T.TIME_SLOT_CODE

-- 지역 정보 조인
LEFT JOIN REGION_MAP R
ON S.PROVINCE_CODE = R.PROVINCE_CODE
AND S.CITY_CODE = R.CITY_CODE
AND S.DISTRICT_CODE = R.DISTRICT_CODE;





-- 서울시 유동 인구 데이터의 가독성을 높이기 위해 지역 및 시간대명을 포함한 뷰 생성
CREATE TABLE MY_HACKATHON_DB.PUBLIC.POPULATION_KOR_LABELING AS
WITH

-- 시간대 코드 매핑 (M03)
TIME_SLOT_MAP AS (
    SELECT 
        SUB_CODE AS TIME_SLOT_CODE, 
        SUB_CODE_NAME AS TIME_SLOT_NAME
    FROM MY_HACKATHON_DB.PUBLIC.CARD_CODE_DATA
    WHERE CODE_ID = 'M03'
),

-- 지역 코드 매핑
REGION_MAP AS (
    SELECT 
        PROVINCE_CODE, 
        CITY_CODE, 
        DISTRICT_CODE,
        PROVINCE_KOR_NAME AS PROVINCE_NAME,
        CITY_KOR_NAME AS CITY_NAME,
        DISTRICT_KOR_NAME AS DISTRICT_NAME
    FROM MY_HACKATHON_DB.PUBLIC.REGION_DATA
)

-- 최종 SELECT: 코드 → 한글명 순서로 가독성 향상
SELECT 
    P.PROVINCE_CODE,
    R.PROVINCE_NAME,
    P.CITY_CODE,
    R.CITY_NAME,
    P.DISTRICT_CODE,
    R.DISTRICT_NAME,
    P.STANDARD_YEAR_MONTH,
    P.WEEKDAY_WEEKEND,
    P.GENDER,
    P.AGE_GROUP,
    P.TIME_SLOT,
    T.TIME_SLOT_NAME,
    P.RESIDENTIAL_POPULATION,
    P.WORKING_POPULATION,
    P.VISITING_POPULATION
FROM MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA P
LEFT JOIN REGION_MAP R
    ON P.PROVINCE_CODE = R.PROVINCE_CODE
    AND P.CITY_CODE = R.CITY_CODE
    AND P.DISTRICT_CODE = R.DISTRICT_CODE
LEFT JOIN TIME_SLOT_MAP T
    ON P.TIME_SLOT = T.TIME_SLOT_CODE;



SELECT * FROM SALES_KOR_LABELING;
SELECT * FROM MY_HACKATHON_DB.PUBLIC.POPULATION_KOR_LABELING;



DESC TABLE MY_HACKATHON_DB.PUBLIC.SALES_KOR_LABELING;
DESC TABLE MY_HACKATHON_DB.PUBLIC.POPULATION_KOR_LABELING;



