-- USE DATABASE MY_HACKATHON_DB;
-- USE SCHEMA PUBLIC;
-- USE WAREHOUSE COMPUTE_WH;

-- CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.DEP_STORE_DATA AS
-- SELECT * FROM LOPLAT_DB.PUBLIC.SNOWFLAKE_STREAMLIT_HACKATHON_LOPLAT_DEPARTMENT_STORE_DATA;

-- CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_POPULATION_DATA AS
-- SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.FLOATING_POPULATION_INFO;

-- CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_CARD_SALES_DATA AS
-- SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO;

-- CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.SEOUL_WEATHER_DATA AS
-- SELECT * FROM SEOUL_TEMPERATURE__RAINFALL.PUBLIC.SNOWFLAKE_STREAMLIT_HACKATHON_LOPLAT_SEOUL_TEMPERATURE_RAINFALL;

-- SELECT * FROM MY_HACKATHON_DB.PUBLIC.SEOUL_WEATHER_DATA LIMIT 100;

-- CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.CARD_DATA AS
-- SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO;

SELECT DISTINCT PROVINCE_CODE FROM MY_HACKATHON_DB.PUBLIC.CARD_DATA;
SELECT DISTINCT CITY_CODE FROM MY_HACKATHON_DB.PUBLIC.CARD_DATA;
SELECT DISTINCT DISTRICT_CODE FROM MY_HACKATHON_DB.PUBLIC.CARD_DATA;

-- CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA AS
-- SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST;

ALTER TABLE MY_HACKATHON_DB.PUBLIC.REGION_DATA
DROP COLUMN PROVINCE_ENG_NAME, CITY_ENG_NAME, DISTRICT_ENG_NAME;

DROP TABLE IF EXISTS MY_HACKATHON_DB.PUBLIC.CARD_REGION_DATA;

CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.CARD_REGION_DATA AS
SELECT
    -- 먼저 지역 정보 열
    RD.CITY_KOR_NAME,
    RD.DISTRICT_KOR_NAME,

    -- 그다음 카드 관련 열
    CD.STANDARD_YEAR_MONTH,
    CD.CARD_TYPE,
    CD.WEEKDAY_WEEKEND,
    CD.GENDER,
    CD.AGE_GROUP,
    CD.TIME_SLOT,
    CD.LIFESTYLE,

    -- SALES
    CD.TOTAL_SALES,
    CD.FOOD_SALES,
    CD.COFFEE_SALES,
    CD.ENTERTAINMENT_SALES,
    CD.DEPARTMENT_STORE_SALES,
    CD.LARGE_DISCOUNT_STORE_SALES,
    CD.SMALL_RETAIL_STORE_SALES,
    CD.CLOTHING_ACCESSORIES_SALES,
    CD.SPORTS_CULTURE_LEISURE_SALES,
    CD.ACCOMMODATION_SALES,
    CD.TRAVEL_SALES,
    CD.BEAUTY_SALES,
    CD.HOME_LIFE_SERVICE_SALES,
    CD.EDUCATION_ACADEMY_SALES,
    CD.MEDICAL_SALES,
    CD.ELECTRONICS_FURNITURE_SALES,
    CD.CAR_SALES,
    CD.CAR_SERVICE_SUPPLIES_SALES,
    CD.GAS_STATION_SALES,
    CD.E_COMMERCE_SALES,

    -- COUNT
    CD.TOTAL_COUNT,
    CD.FOOD_COUNT,
    CD.COFFEE_COUNT,
    CD.ENTERTAINMENT_COUNT,
    CD.DEPARTMENT_STORE_COUNT,
    CD.LARGE_DISCOUNT_STORE_COUNT,
    CD.SMALL_RETAIL_STORE_COUNT,
    CD.CLOTHING_ACCESSORIES_COUNT,
    CD.SPORTS_CULTURE_LEISURE_COUNT,
    CD.ACCOMMODATION_COUNT,
    CD.TRAVEL_COUNT,
    CD.BEAUTY_COUNT,
    CD.HOME_LIFE_SERVICE_COUNT,
    CD.EDUCATION_ACADEMY_COUNT,
    CD.MEDICAL_COUNT,
    CD.ELECTRONICS_FURNITURE_COUNT,
    CD.CAR_SALES_COUNT,
    CD.CAR_SERVICE_SUPPLIES_COUNT,
    CD.GAS_STATION_COUNT,
    CD.E_COMMERCE_COUNT,

    RD.DISTRICT_GEOM

FROM MY_HACKATHON_DB.PUBLIC.CARD_DATA AS CD
LEFT JOIN MY_HACKATHON_DB.PUBLIC.REGION_DATA AS RD
USING (PROVINCE_CODE, CITY_CODE, DISTRICT_CODE);


ALTER TABLE MY_HACKATHON_DB.PUBLIC.CARD_REGION_DATA
DROP COLUMN DISTRICT_GEOM;

SELECT * FROM MY_HACKATHON_DB.PUBLIC.CARD_REGION_DATA LIMIT 100;

SELECT DISTINCT CITY_KOR_NAME FROM MY_HACKATHON_DB.PUBLIC.CARD_REGION_DATA;
SELECT DISTINCT DISTRICT_KOR_NAME FROM MY_HACKATHON_DB.PUBLIC.CARD_REGION_DATA;

CREATE OR REPLACE TABLE MY_HACKATHON_DB.PUBLIC.DEPARTMENT_CARD_DATA AS
SELECT *
FROM MY_HACKATHON_DB.PUBLIC.CARD_REGION_DATA
WHERE DISTRICT_KOR_NAME IN ('여의도동', '반포동', '소공동');

SELECT * FROM MY_HACKATHON_DB.PUBLIC.DEPARTMENT_CARD_DATA;


SELECT * FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CODE_MASTER